# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\"=\n\tTimestamp\x12\x0f\n\x07started\x18\x01 \x01(\x03\x12\r\n\x05\x65nded\x18\x02 \x01(\x03\x12\x10\n\x08\x64uration\x18\x03 \x01(\x02\"\x83\x01\n\x04Span\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12\x0f\n\x07traceID\x18\x02 \x01(\t\x12\x0e\n\x06spanID\x18\x03 \x01(\t\x12\x14\n\x0cparentSpanID\x18\x04 \x01(\t\x12\x10\n\x08spanName\x18\x05 \x01(\t\x12\x1d\n\ttimestamp\x18\x06 \x01(\x0b\x32\n.Timestamp\"+\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2$\n\x07Storage\x12\x19\n\x05Store\x12\x05.Span\x1a\t.ResponseB\x12Z\x10./btrace_storageb\x06proto3')



_TIMESTAMP = DESCRIPTOR.message_types_by_name['Timestamp']
_SPAN = DESCRIPTOR.message_types_by_name['Span']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Timestamp = _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMP,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:Timestamp)
  })
_sym_db.RegisterMessage(Timestamp)

Span = _reflection.GeneratedProtocolMessageType('Span', (_message.Message,), {
  'DESCRIPTOR' : _SPAN,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:Span)
  })
_sym_db.RegisterMessage(Span)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_STORAGE = DESCRIPTOR.services_by_name['Storage']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\020./btrace_storage'
  _TIMESTAMP._serialized_start=17
  _TIMESTAMP._serialized_end=78
  _SPAN._serialized_start=81
  _SPAN._serialized_end=212
  _RESPONSE._serialized_start=214
  _RESPONSE._serialized_end=257
  _STORAGE._serialized_start=259
  _STORAGE._serialized_end=295
# @@protoc_insertion_point(module_scope)
