# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x1a\x1bgoogle/protobuf/empty.proto\"D\n\x10StorageTimestamp\x12\x0f\n\x07started\x18\x01 \x01(\x03\x12\r\n\x05\x65nded\x18\x02 \x01(\x03\x12\x10\n\x08\x64uration\x18\x03 \x01(\x02\"\x91\x01\n\x0bStorageSpan\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12\x0f\n\x07traceID\x18\x02 \x01(\t\x12\x0e\n\x06spanID\x18\x03 \x01(\t\x12\x14\n\x0cparentSpanID\x18\x04 \x01(\t\x12\x10\n\x08spanName\x18\x05 \x01(\t\x12$\n\ttimestamp\x18\x06 \x01(\x0b\x32\x11.StorageTimestamp\"=\n\x0fStorageResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\t\n\x01l\x18\x03 \x03(\t\"\x1b\n\x0bServiceName\x12\x0c\n\x04name\x18\x01 \x01(\t\"?\n\x0fServiceResponse\x12\x0f\n\x07traceId\x18\x01 \x01(\t\x12\x1b\n\x05spans\x18\x02 \x03(\x0b\x32\x0c.StorageSpan\"[\n\x0bServicePair\x12!\n\x0bserviceName\x18\x01 \x01(\x0b\x32\x0c.ServiceName\x12)\n\x0fserviceResponse\x18\x02 \x01(\x0b\x32\x10.ServiceResponse2\x8b\x02\n\x07Storage\x12\'\n\x05Store\x12\x0c.StorageSpan\x1a\x10.StorageResponse\x12\x35\n\x0bGetServices\x12\x16.google.protobuf.Empty\x1a\x0c.ServiceName0\x01\x12\x30\n\x0eGetServiceData\x12\x0c.ServiceName\x1a\x10.ServiceResponse\x12;\n\x17GetMultipleServicesData\x12\x0c.ServiceName\x1a\x10.ServiceResponse(\x01\x12\x31\n\x07GetData\x12\x16.google.protobuf.Empty\x1a\x0c.ServicePair0\x01\x42\x12Z\x10./btrace_storageb\x06proto3')



_STORAGETIMESTAMP = DESCRIPTOR.message_types_by_name['StorageTimestamp']
_STORAGESPAN = DESCRIPTOR.message_types_by_name['StorageSpan']
_STORAGERESPONSE = DESCRIPTOR.message_types_by_name['StorageResponse']
_SERVICENAME = DESCRIPTOR.message_types_by_name['ServiceName']
_SERVICERESPONSE = DESCRIPTOR.message_types_by_name['ServiceResponse']
_SERVICEPAIR = DESCRIPTOR.message_types_by_name['ServicePair']
StorageTimestamp = _reflection.GeneratedProtocolMessageType('StorageTimestamp', (_message.Message,), {
  'DESCRIPTOR' : _STORAGETIMESTAMP,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:StorageTimestamp)
  })
_sym_db.RegisterMessage(StorageTimestamp)

StorageSpan = _reflection.GeneratedProtocolMessageType('StorageSpan', (_message.Message,), {
  'DESCRIPTOR' : _STORAGESPAN,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:StorageSpan)
  })
_sym_db.RegisterMessage(StorageSpan)

StorageResponse = _reflection.GeneratedProtocolMessageType('StorageResponse', (_message.Message,), {
  'DESCRIPTOR' : _STORAGERESPONSE,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:StorageResponse)
  })
_sym_db.RegisterMessage(StorageResponse)

ServiceName = _reflection.GeneratedProtocolMessageType('ServiceName', (_message.Message,), {
  'DESCRIPTOR' : _SERVICENAME,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:ServiceName)
  })
_sym_db.RegisterMessage(ServiceName)

ServiceResponse = _reflection.GeneratedProtocolMessageType('ServiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVICERESPONSE,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:ServiceResponse)
  })
_sym_db.RegisterMessage(ServiceResponse)

ServicePair = _reflection.GeneratedProtocolMessageType('ServicePair', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEPAIR,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:ServicePair)
  })
_sym_db.RegisterMessage(ServicePair)

_STORAGE = DESCRIPTOR.services_by_name['Storage']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\020./btrace_storage'
  _STORAGETIMESTAMP._serialized_start=46
  _STORAGETIMESTAMP._serialized_end=114
  _STORAGESPAN._serialized_start=117
  _STORAGESPAN._serialized_end=262
  _STORAGERESPONSE._serialized_start=264
  _STORAGERESPONSE._serialized_end=325
  _SERVICENAME._serialized_start=327
  _SERVICENAME._serialized_end=354
  _SERVICERESPONSE._serialized_start=356
  _SERVICERESPONSE._serialized_end=419
  _SERVICEPAIR._serialized_start=421
  _SERVICEPAIR._serialized_end=512
  _STORAGE._serialized_start=515
  _STORAGE._serialized_end=782
# @@protoc_insertion_point(module_scope)
