# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\"D\n\x10StorageTimestamp\x12\x0f\n\x07started\x18\x01 \x01(\x03\x12\r\n\x05\x65nded\x18\x02 \x01(\x03\x12\x10\n\x08\x64uration\x18\x03 \x01(\x02\"\x91\x01\n\x0bStorageSpan\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12\x0f\n\x07traceID\x18\x02 \x01(\t\x12\x0e\n\x06spanID\x18\x03 \x01(\t\x12\x14\n\x0cparentSpanID\x18\x04 \x01(\t\x12\x10\n\x08spanName\x18\x05 \x01(\t\x12$\n\ttimestamp\x18\x06 \x01(\x0b\x32\x11.StorageTimestamp\"2\n\x0fStorageResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t22\n\x07Storage\x12\'\n\x05Store\x12\x0c.StorageSpan\x1a\x10.StorageResponseB\x12Z\x10./btrace_storageb\x06proto3')



_STORAGETIMESTAMP = DESCRIPTOR.message_types_by_name['StorageTimestamp']
_STORAGESPAN = DESCRIPTOR.message_types_by_name['StorageSpan']
_STORAGERESPONSE = DESCRIPTOR.message_types_by_name['StorageResponse']
StorageTimestamp = _reflection.GeneratedProtocolMessageType('StorageTimestamp', (_message.Message,), {
  'DESCRIPTOR' : _STORAGETIMESTAMP,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:StorageTimestamp)
  })
_sym_db.RegisterMessage(StorageTimestamp)

StorageSpan = _reflection.GeneratedProtocolMessageType('StorageSpan', (_message.Message,), {
  'DESCRIPTOR' : _STORAGESPAN,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:StorageSpan)
  })
_sym_db.RegisterMessage(StorageSpan)

StorageResponse = _reflection.GeneratedProtocolMessageType('StorageResponse', (_message.Message,), {
  'DESCRIPTOR' : _STORAGERESPONSE,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:StorageResponse)
  })
_sym_db.RegisterMessage(StorageResponse)

_STORAGE = DESCRIPTOR.services_by_name['Storage']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\020./btrace_storage'
  _STORAGETIMESTAMP._serialized_start=17
  _STORAGETIMESTAMP._serialized_end=85
  _STORAGESPAN._serialized_start=88
  _STORAGESPAN._serialized_end=233
  _STORAGERESPONSE._serialized_start=235
  _STORAGERESPONSE._serialized_end=285
  _STORAGE._serialized_start=287
  _STORAGE._serialized_end=337
# @@protoc_insertion_point(module_scope)
